// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package pgdb

import (
	"database/sql"

	"github.com/google/uuid"
)

type Author struct {
	ID   uuid.UUID
	Name string
	Bio  sql.NullString
	Foo  sql.NullString
}
